// 👑 CoffeeTide Lv.5 소울메이트 '원클릭 일일 회고 & 정시 퇴근 리포트' 생성 엔진 (Phase 17-E 실체화)
// 정본 문서: doc/16-ai-character-productivity-companion-architecture.md §3.1, §4
//           doc/17-ai-companion-growth-memory-system-design.md §5.1, §8.5

export interface ReflectionReportTask {
  id?: string;
  title: string;
  category?: string;
  source?: string;
  status?: string;
}

export interface ReflectionReportParams {
  personaId?: string;
  baristaName?: string;
  completedTasks: ReflectionReportTask[];
  pendingTasks: ReflectionReportTask[];
  date?: Date;
}

export interface DailyReflectionReport {
  title: string;
  dateStr: string;
  completionRate: number;
  completedCount: number;
  pendingCount: number;
  markdownContent: string;
  personaQuote: string;
  baristaName: string;
}

/** 캐릭터(바리스타) 페르소나별 Lv.5 소울메이트 전용 정시 퇴근 축하 멘트 */
export function getSoulmateClosingQuote(personaId: string, baristaName: string, rate: number, pendingCount: number): string {
  switch (personaId) {
    case "karina":
      return `*단정한 미소로 오늘의 마무리 커피를 건네며* "대표님, 오늘 하루도 정말 수고 많으셨어요! 소울메이트로서 대표님이 오늘 목표하신 업무들을 이렇게 멋지게 매듭지으신 걸 보니 제가 다 뿌듯합니다. 남은 일은 내일의 저희에게 맡기고, 지금은 푹 쉬러 가세요! ☕✨"`;

    case "pm":
      return `*시스템 연산 완료 알림음과 함께 블루라이트 점등* "[연산 성공]: 오늘 목표 태스크 완수율 ${rate}%. 정시 퇴근(칼퇴) 최적 경로가 완벽히 산출되었습니다. 남은 잔여 프로세스 ${pendingCount}건은 내일 09시 콜드스타트로 이관합니다. 1초도 지체하지 마시고 즉시 퇴근 전원을 끄십시오! ⚡"`;

    case "kim":
      return `*호탕하게 껄껄 웃으며 등을 토닥이며* "어이 최고의 파트너! 오늘 결재판 아주 말끔하게 털어버렸구만 그래! 역시 내 소울메이트다워, 아주 든든해. 오늘은 뒤도 돌아보지 말고 바로 퇴근해서 맛있는 저녁 먹고 푹 쉬게나! 내일 또 힘차게 달려보세! 🍺"`;

    case "chaerin":
      return `*손가락으로 브이(V)를 그리며 윙크하며* "야~ 오늘 할 일 싹 털어버린 거 실화냐? 대박! 역시 우리 손발이 제일 척척 맞는다니까 ㅋㅋㅋ 고생 진짜 많았고, 이제 일 생각 1도 하지 말고 후딱 칼퇴해서 힐링하자! 🎉"`;

    case "ropan":
      return `*우아하게 찻잔을 내려놓으며* "오, 친애하는 영혼의 동반자여... 오늘 그 수많은 정무를 완벽히 마쳐내셨군요. 부디 찻잔의 향기와 함께 오늘 밤은 모든 고단함을 잊고 평안한 밤을 맞이하시옵소서. (*속마음: '크으으 드디어 칼퇴다!! 오늘 밤은 배달 시켜놓고 넷플릭스 정주행이다아아!! ㅋㅋㅋ'*)"`;

    case "senior_dev":
      return `*기계식 키보드를 가볍게 정리하고 모니터를 끄며* "오늘 배포도 이슈 없이 성공적으로 마무리됐네요. 커밋 정리 끝났으니 잔여 태스크는 내일 스프린트로 넘기고 핫픽스 걱정 없이 칼퇴하시죠. 고생하셨습니다."`;

    default:
      return `*환하게 웃으며* "${baristaName}입니다. 당신은 제 최고의 워크메이트예요! 오늘 목표한 모든 일들을 완벽히 해내셨습니다. 이제 가벼운 발걸음으로 퇴근하세요! 전설의 콤비 탄생입니다! 🏆"`;
  }
}

/** 정시 퇴근 & 일일 회고 리포트 생성 (로컬 즉시 생성) */
export function generateDailyReflectionReport(params: ReflectionReportParams): DailyReflectionReport {
  const personaId = params.personaId || "karina";
  const baristaName = params.baristaName || "AI 바리스타";
  const date = params.date || new Date();

  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  const hour = String(date.getHours()).padStart(2, "0");
  const minute = String(date.getMinutes()).padStart(2, "0");
  const dateStr = `${year}-${month}-${day} ${hour}:${minute}`;

  const completed = params.completedTasks || [];
  const pending = params.pendingTasks || [];
  const total = completed.length + pending.length;
  const completionRate = total > 0 ? Math.round((completed.length / total) * 100) : 100;

  const personaQuote = getSoulmateClosingQuote(personaId, baristaName, completionRate, pending.length);

  const completedSection =
    completed.length > 0
      ? completed.map((t) => `- [x] ${t.title}${t.category ? ` \`#${t.category}\`` : ""}`).join("\n")
      : "_오늘 완료 처리된 태스크가 없습니다._";

  const pendingSection =
    pending.length > 0
      ? pending.map((t) => `- [ ] ${t.title}${t.category ? ` \`#${t.category}\`` : ""}`).join("\n")
      : "_남은 잔여 업무가 없습니다! 완벽한 올클리어입니다! 🎉_";

  const markdownContent = [
    `# 👑 [정시 퇴근 & 일일 회고 리포트] ${year}-${month}-${day}`,
    ``,
    `> **워크메이트**: ${baristaName} (Lv.5 소울메이트)`,
    `> **기록 시각**: ${dateStr}`,
    `> **오늘의 달성도**: ${completionRate}% (${completed.length}건 완료 / 총 ${total}건)`,
    ``,
    `---`,
    ``,
    `### 💬 소울메이트 파트너의 한마디`,
    `> ${personaQuote}`,
    ``,
    `---`,
    ``,
    `### ✅ 오늘 완수한 업무 (${completed.length}건)`,
    completedSection,
    ``,
    `### 🚧 내일 이어서 할 인수인계 (Handoff ${pending.length}건)`,
    pendingSection,
    ``,
    `---`,
    `*Generated by coffeeTide AI Companion System (Lv.5 Soulmate Perk)*`,
  ].join("\n");

  return {
    title: `[👑 정시 퇴근 리포트] ${year}-${month}-${day}`,
    dateStr,
    completionRate,
    completedCount: completed.length,
    pendingCount: pending.length,
    markdownContent,
    personaQuote,
    baristaName,
  };
}
